# Generated by Django 5.2.17 on 2026-09-16 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("max_borrow_quantity", models.PositiveIntegerField(default=1)),
                ("image", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_models",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "manufacturer", "model_number"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=80, unique=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("OVERDUE", "Overdue"),
                            ("MAINTENANCE", "Maintenance"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="inventory.equipmentmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="equipmentmodel",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "model_number", "name"),
                name="unique_equipment_model_identity",
            ),
        ),
    ]
