# Generated by Django 5.2.17 on 2026-09-16 10:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_active_loans_per_user", models.PositiveIntegerField(default=3)),
                ("max_units_per_booking", models.PositiveIntegerField(default=5)),
                (
                    "default_late_fee_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "system settings",
                "verbose_name_plural": "system settings",
            },
        ),
    ]
